version: "3.8"

services:
  # backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    # Only build development stage from Dockerfile
      target: development
    
    # Reflect File changes from host to container
    volumes:
      - ./backend:/webchat/src/app
      - /webchat/src/app/node_modules/
    # RUN in debug mode: npm run start:debug
    # Run in dev mode: 
    command: npm run start:dev
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  
  # Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/webchat/frontend/src/app
      - /webchat/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - backend   

  # Postgres Database for NestJS to connect to
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  # Postgres Admin tool 
  postgres_admin:
    image: dpage/pgadmin4:7.5
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: dil@dil.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
      
